---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r message=FALSE}
unzip("activity.zip")
rawdata<- read.csv("activity.csv")

head(rawdata)
```

## What is mean total number of steps taken per day?

```{r message=FALSE}
# 1. Make a histogram of the total number of steps taken each day
library(dplyr)
rawdata <- tbl_df(rawdata)
stepsSum <- summarize(
    group_by(rawdata, date), 
    stepsSumPerDay =sum(steps, na.rm=T)
    )# steps per day

library(ggplot2)
qplot(date, weight=stepsSumPerDay, data = stepsSum, geom="histogram", ylab="StepsSum per Day")


#  2. Calculate and report the mean and median total number of steps taken per day
StepsMeanAndMedian <- summarize(group_by(rawdata, date), 
          stepsMeanPerDay = mean(steps, na.rm = T), 
          stepsMedianPerDay = median(steps, na.rm =T)) # 

head(StepsMeanAndMedian)

```

## What is the average daily activity pattern?

```{r message=FALSE}
# 1. Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
stepsInterval <- summarize(
    group_by(rawdata, interval), 
    stepsIntervalMean = mean(steps, na.rm=T)
    )

with(stepsInterval, 
     plot(interval, stepsIntervalMean, type = "l")
     )

# 2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
stepsInterval[
    which.max(
        stepsInterval$stepsIntervalMean
        )
    ,
    ]

```



## Imputing missing values

```{r message=FALSE}
#  1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
sum(is.na(rawdata))
colSums(is.na(rawdata))

# 2. Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

stepsMean <- aggregate(steps~interval, data = rawdata, mean) # averaged steps grouped by interval

for (i in which(is.na(rawdata))) {
    rawdata[i, 1]  <-  stepsMean[
        which(
            stepsMean$interval %in% rawdata[i, 3]),
            2
        ]
}  # replace NA with averaged steps for that 5-minute interval

anyNA(rawdata)  # validate if there is any NA in data

```



## Are there differences in activity patterns between weekdays and weekends?

```{r message=FALSE}

# 1. Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

library(lubridate)
rawdata$weekTime <- wday(rawdata$date) # weekTime: 1 is Sunday, 2 is Monday...

for (i in 1:nrow(rawdata))  {
    if (any(rawdata[i,4] == 2:6))  {rawdata[i,4] <- "weekday"}
    else {rawdata[i, 4] <- "weekend" }
}

# 2. Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.
stepsMean2 <- aggregate(steps~interval+weekTime, data = rawdata, mean)

library(ggplot2)
qplot(interval, steps, data = stepsMean2, facets = weekTime~. , geom="line")

```

